# Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Info
title: "mrclmlt"
description: "Em construção (para variar)"

# links
url: "https://blog.mrclmlt.com.br"
baseurl: ""

# Plugim obrigatório
plugins:
  - jekyll-include-cache

# Equivalente a <html lang="pt-BR">
locale: "pt-BR"

# aparentemente desativa o feed padrão do jekyll e ativa o personalizado na raiz
feed:
  path: feed-desativado.xml
