# Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Info
title: "Blog"
description: "Em breve"

# links
url: "https://github.io"
baseurl: "/blog"

# Plugim obrigatório
plugins:
  - jekyll-include-cache

# Equivalente a <html lang="pt-BR">
locale: "pt-BR"
